CREATE TABLE User (
id INT AUTO_INCREMENT NOT NULL,
email VARCHAR(100) UNIQUE NOT NULL,
password VARCHAR(255)NOT NULL,
fullName VARCHAR(100) NOT NULL,
active TINYINT(1) DEFAULT 1,
PRIMARY KEY(id)
);

CREATE TABLE Tweet (
id INT AUTO_INCREMENT NOT NULL,
user_id INT NOT NULL,
text VARCHAR(140) NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE `Comment` (
id INT AUTO_INCREMENT NOT NULL ,
user_id INT NOT NULL,
tweet_id INT NOT NULL ,
creation_date DATETIME NOT NULL ,
text VARCHAR(60) NOT NULL ,
PRIMARY KEY (id),
FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE,
FOREIGN KEY (tweet_id) REFERENCES Tweet(id) ON DELETE CASCADE
);

CREATE TABLE Messages(
id int AUTO_INCREMENT,
author_id int NOT NULL,
receiver_id int NOT NULL,
title VARCHAR (30) NOT NULL,
text VARCHAR (60) NOT NULL,
status TINYINT(1) DEFAULT 1,
PRIMARY KEY (id),
FOREIGN KEY(author_id) REFERENCES User (id)  ON DELETE CASCADE,
FOREIGN KEY(receiver_id) REFERENCES User (id)  ON DELETE CASCADE
)